---
- name: Generate Configs using AVD
  hosts: all
  gather_facts: false

  tasks:
    - name: Generate Device Configurations and Documentation
      tags: ['build']
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Deploy device configuration
      tags: ['never', 'deploy']
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_eapi