tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: SVC_ETHERNET
    mac_vrf_vni_base: 10000
    vrfs:
      - name: 'ETHERNET_VPN'
        vrf_id: 11
        address_families:
          - evpn
        vtep_diagnostic:
          loopback: 1001
          loopback_description: SVC_ETHERNET_LOOPBACK
          loopback_ip_range: 10.1.255.0/24
        svis:
          - id: 1013
            name: SVC01_C1_VLAN_SITE01_PE03
            enabled: True
            ip_address_virtual: 10.1.3.1/24
            tags: ['node03']

          - id: 1014
            name: SVC01_C1_VLAN_SITE01_PE04
            enabled: True
            ip_address_virtual: 10.1.4.1/24
            tags: ['node04']

          - id: 1015
            name: SVC01_C1_VLAN_SITE02_PE01
            enabled: True
            ip_address_virtual: 10.1.5.1/24
            tags: ['site02']
