---
device_id: "{{ rid.split('.')[3] }}"
hostname: "{{ inventory_hostname }}"

local_users:
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true
    # sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  - name: ansible
    privilege: 15
    role: network-admin
    # password: ansible
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

  - name: arista
    privilege: 15
    role: network-admin
    # password: arista
    sha512_password: "$6$7WhvEi5Ce5f5Ut3z$Ethmha7rb710RKsaVteusVOuNP1Utfjzse58xxbgiZp4MF0fp7BX5lAw8yBgv/HWCihVomuCSrsJx8wKnJ7Tm1"

  - name: tom
    privilege: 15
    role: network-admin
    # password: arista123
    sha512_password: "$6$TyWn7NeXe/vBRl1t$S4fEOkPmpTGz7TLHCzDNP8D2UfpO3ciC2MuGmCaFMVF3B7zt9KSnt9yq99y69XBIY1HV/kO4QjOk32yRQOru5."

static_routes:
- vrf: default
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.2.1

management_ssh:
  enable: True
  vrfs:
    - name: default
      enable: True

# dns servers.
name_servers:
  - 192.168.2.1
  - 8.8.8.8

timezone: Europe/Paris
ntp:
  local_interface:
    name: Management0
    vrf: default
  servers:
    - name: fr.pool.ntp.org
      preferred: True
      local_interface: Management0
      vrf: default
      burst: True
      iburst: True
    - name: uk.pool.ntp.org
      local_interface: Management0
      vrf: default
      burst: True
      iburst: True

# dns domain
dns_domain: atd.lab

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
# ntp_servers:
#  - 192.168.0.1

aaa_authorization:
  exec:
    default: local

service_routing_protocols_model: multi-agent
ip_routing: true

vrfs:
- name: default
  ip_routing: true


management_interfaces:
- name: Management0
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: "{{ ansible_host }}/24"
  gateway: 192.168.2.1
  type: oob

management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true