asn: 65000

loopback_interfaces:
  - name: Loopback0
    description: "Router ID"
    shutdown: False
    vrf: default
    ip_address: "{{ rid }}/32"
    isis_enable: "CORE-ISIS"
    isis_passive: True
    node_segment:
      ipv4_index: "{{ rid.split('.')[3] }}"

mpls:
  ip: True

router_traffic_engineering:
  # enabled: True
  segment_routing:
    colored_tunnel_rib: True

router_isis:
  instance: "CORE-ISIS"
  net: "{%if rid.split('.')[3] | length == 3 %}49.0192.0168.0000.0{{ rid.split('.')[3] }}.00{% else %}49.0192.0168.0000.00{{ rid.split('.')[3] }}.00{%endif%}"
  router_id: "{{ rid }}"
  is_type: level-2
  log_adjacency_changes: True
  advertise:
    passive_only: True
  address_family_ipv4:
    enabled: True
    fast_reroute_ti_lfa:
      mode: "link-protection"
  segment_routing_mpls:
    enabled: True
    router_id: "{{rid}}"
    prefix_segments:
      # S1 PE to P
      - prefix: "10.0.1.0/31"
        index: 50010
      - prefix: "10.0.1.2/31"
        index: 50012
      - prefix: "10.0.1.4/31"
        index: 50014
      - prefix: "10.0.1.6/31"
        index: 50016
      - prefix: "10.0.1.8/31"
        index: 50018
      - prefix: "10.0.1.10/31"
        index: 50100
      - prefix: "10.0.1.12/31"
        index: 50112
      - prefix: "10.0.1.14/31"
        index: 50114
      # P to P
      - prefix: "10.0.0.0/31"
        index: 50000
      - prefix: "10.0.0.2/31"
        index: 50002
      - prefix: "10.0.0.4/31"
        index: 50004
      - prefix: "10.0.0.6/31"
        index: 50006
      - prefix: "10.0.0.8/31"
        index: 50008
      # S1 PE to P
      - prefix: "10.0.2.0/31"
        index: 50020
      - prefix: "10.0.2.2/31"
        index: 50022