
router_bgp:
  as: "{{ asn }}"
  router_id: "{{ rid }}"
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  address_family_evpn:
    peer_groups:
      - name: EVPN-CORE
        activate: True
        encapsulation: "mpls"
    neighbor_default:
      encapsulation: "mpls"
      next_hop_self_source_interface: Loopback0
  peer_groups:
    - name: EVPN-CORE
      update_source: Loopback0
      route_reflector_client: True
      type: ipv4
      send_community: all
  neighbors:
    # PE Site 1
    - ip_address: "{{ hostvars['s1-pe01'].rid }}"
      peer_group: EVPN-CORE
      remote_as: "{{ asn }}"
      description: "{{ hostvars['s1-pe01'].inventory_hostname }}"
    - ip_address: "{{ hostvars['s1-pe02'].rid }}"
      peer_group: EVPN-CORE
      remote_as: "{{ asn }}"
      description: "{{ hostvars['s1-pe02'].inventory_hostname }}"
    - ip_address: "{{ hostvars['s1-pe03'].rid }}"
      peer_group: EVPN-CORE
      remote_as: "{{ asn }}"
      description: "{{ hostvars['s1-pe03'].inventory_hostname }}"
    - ip_address: "{{ hostvars['s1-pe04'].rid }}"
      peer_group: EVPN-CORE
      remote_as: "{{ asn }}"
      description: "{{ hostvars['s1-pe04'].inventory_hostname }}"
    # PE Site 2
    - ip_address: "{{ hostvars['s2-pe01'].rid }}"
      peer_group: EVPN-CORE
      remote_as: "{{ asn }}"
      description: "{{ hostvars['s2-pe01'].inventory_hostname }}"
