vlans:
  - id: 1810
    name: "S1-FW-XCO"
    tenant: "FW-HA"
  - id: 2001
    name: "BKP-SITE01"
    tenant: "BKP"

loopback_interfaces:
  - name: Loopback0
    description: "Router ID"
    shutdown: False
    vrf: default
    ip_address: "{{ rid }}/32"
    isis_enable: "CORE-ISIS"
    isis_passive: True
    node_segment:
      ipv4_index: "{{ device_id }}"
  - name: Loopback1018
    description: "Router ID"
    shutdown: False
    vrf: FW-HA
    ip_address: "1.18.10.{{ device_id }}/32"
