vlans:
  - id: 1811
    name: "S2-REMOTE-END-XCO"
    tenant: "FW-HA"
  - id: 2002
    name: "BKP-SITE02"
    tenant: "BKP"

vlan_interfaces:
- name: "Vlan2002"
  description: vrf-bkp-backup-flows
  shutdown: False
  vrf: BKP
  ip_address: "10.200.2.{{ device_id }}/24"
  ip_virtual_router_addresses:
    - "10.200.2.1"

- name: "Vlan1811"
  description: vrf-FW-HA-xco-remote-end-site02
  shutdown: False
  vrf: FW-HA
  ip_address: "10.18.11.{{ device_id }}/24"
  ip_virtual_router_addresses:
    - "10.18.11.1"