vlans:
  - name: SVC01_C1_VLAN_SITE01_PE04
    id: 1014

ethernet_interfaces:
  - name: Ethernet1
    description: to s1-pe04 ethernet4
    vlans: "1-4094"
    mode: "trunk"


port_channel_interfaces:

vlan_interfaces:
- name: "Vlan1013"
  description: SVC01_C1_VLAN_SITE01_PE04 - VRF ETHERNET_VPN
  shutdown: False
  vrf: ETHERNET_VPN
  ip_address: "10.1.4.{{ device_id }}/24"
#   vrrp_ids:
#     - id: 10
#       priority_level: 100
#       ipv4:
#         address: 10.18.10.254
#         version: 3

# - name: "Vlan2001"
#   description: vrf-bkp-xco-site01
#   shutdown: False
#   vrf: BKP
#   ip_address: "10.200.1.{{ device_id }}/24"

static_routes:
  - vrf: "{{ management_vrf_name }}"
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.2.1
  - vrf: ETHERNET_VPN
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.4.1