vlans:
  - name: SVC01_C1_VLAN_SITE01_PE03
    id: 1113

ethernet_interfaces:
  - name: Ethernet1
    description: to s1-pe02 ethernet4
    vlans: "1-4094"
    mode: "trunk"

  - name: Ethernet2
    switchport:
      enabled: false
    peer_type: l3_interface
    shutdown: false

  - name: Ethernet2.101
    peer_type: l3_interface
    ip_address: 10.2.0.1/31
    shutdown: false
    description: L3VPN Only USE CASE
    encapsulation_dot1q:
      vlan: 101
    vrf: ATM

port_channel_interfaces:

vlan_interfaces:
- name: "Vlan1113"
  description: SVC01_C1_VLAN_SITE01_PE03 - VRF ETHERNET_VPN
  shutdown: False
  vrf: ETHERNET_VPN
  ip_address: "10.1.3.{{ device_id }}/24"
#   vrrp_ids:
#     - id: 10
#       priority_level: 100
#       ipv4:
#         address: 10.18.10.254
#         version: 3

# - name: "Vlan2001"
#   description: vrf-bkp-xco-site01
#   shutdown: False
#   vrf: BKP
#   ip_address: "10.200.1.{{ device_id }}/24"

static_routes:
  - vrf: "{{ management_vrf_name }}"
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.2.1
  - vrf: ETHERNET_VPN
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.3.1
  - vrf: ATM
    destination_address_prefix: 10.2.254.0/24
    interface: Null0

router_bgp:
  as: '65101'
  updates:
    wait_install: false
  peer_groups:
  - name: MPLS-BACKBONE
    remote_as: '65000'
    description: MPLS CONNECTITVITY
    shutdown: false
    bfd: false
    send_community: all
  vrfs:
  - name: ATM
    redistribute:
      connected:
        enabled: true
      static:
        enabled: true
    address_family_ipv4:
      neighbors:
      - ip_address: 10.2.0.0
        activate: true
    neighbors:
    - ip_address: 10.2.0.0
      peer_group: MPLS-BACKBONE
      description: MPLS CONNECTITVITY S1-PE03
      route_map_out: RM-MARK-ATM-CE03
    updates:
      wait_install: false

prefix_lists:
  - name: PL-ATM-FAKE-PREFIX
    sequence_numbers:
      - sequence: 10
        action: "permit 10.2.254.0/24"

route_maps:
    # Route-map Name.
  - name: RM-MARK-ATM-CE03
    sequence_numbers:
      - sequence: 10
        type: permit
        description: Mark FAKE route with community 65000:12013
        # match:
        #   - "ip address prefix-list PL-ATM-FAKE-PREFIX"
        set:
          - "community 65000:10090 additive"