ethernet_interfaces:
- name: Ethernet1
  peer: s1-p01
  peer_interface: Ethernet1
  description: S1-P01_Ethernet1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.0/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet2
  peer: s1-p02
  peer_interface: Ethernet1
  description: S1-P02_Ethernet1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.2/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet4
  peer: s1-ce01
  shutdown: False
  channel_group:
    id: 4
    mode: "active"

port_channel_interfaces:
- name: Port-Channel4
  description: to s1-ce01 - CLIENT use-case - Firewall emulation VRRP
  mode: "trunk"
  vlans: "1810,2001"
  evpn_ethernet_segment:
    identifier: 0000:0000:0101:0101:0101
    mpls:
      shared_index: 100
    route_target: 01:01:01:01:01:01
    designated_forwarder_election:
      hold_time: 1
  lacp_id: 0101.0101.0101

vlan_interfaces:
- name: "Vlan1810"
  description: vrf-FW-HA-xco-firewall-site01
  shutdown: False
  vrf: FW-HA
  ip_address: "10.18.10.{{ device_id }}/24"
  ip_virtual_router_addresses:
    - "10.18.10.1"

- name: "Vlan2001"
  description: vrf-bkp-backup-flows
  shutdown: False
  vrf: BKP
  ip_address: "10.200.1.{{ device_id }}/24"
  ip_virtual_router_addresses:
    - "10.200.1.1"

router_traffic_engineering:
  # enabled: True
  segment_routing:
    colored_tunnel_rib: True
    policy_endpoints:
      - address: 1.0.0.21
        colors:
          - value: 300
            binding_sid: 1000099
            description: BKP-FLOWS-TO-S2-PE02
            name: BKP-POLICY
            path_group:
              - preference: 100
                # explicit_null: ipv4
                segment_list:
                  - label_stack: "900111 900122 950004 900021"
