ethernet_interfaces:
# --------------------------------- #
# TO PE INTERFACES
# --------------------------------- #
- name: Ethernet1
  peer: s1-pe01
  peer_interface: Ethernet1
  description: S1-PE01_Ethernet1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.1/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet2
  peer: s1-pe02
  peer_interface: Ethernet1
  description: S1-PE02_Ethernet1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.5/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet3
  peer: s1-pe03
  peer_interface: Ethernet1
  description: S1-PE03_Ethernet1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.9/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet4
  peer: s1-pe04
  peer_interface: Ethernet1
  description: S1-PE04_Ethernet1
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.13/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

# --------------------------------- #
# TO P INTERFACES
# --------------------------------- #

- name: Ethernet5
  peer: s1-p02
  peer_interface: Ethernet5
  description: S1-P02_Ethernet5
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.0.0/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet6
  peer: s2-p01
  peer_interface: Ethernet6
  description: S2-P01_Ethernet6
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.0.2/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet7
  peer: s2-p02
  peer_interface: Ethernet7
  description: S2-P02_Ethernet7
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.0.4/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True