ethernet_interfaces:
# --------------------------------- #
# TO PE INTERFACES
# --------------------------------- #
- name: Ethernet1
  peer: s1-pe01
  peer_interface: Ethernet2
  description: S1-PE01_Ethernet2
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.3/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet2
  peer: s1-pe02
  peer_interface: Ethernet2
  description: S1-PE02_Ethernet2
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.7/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet3
  peer: s1-pe03
  peer_interface: Ethernet2
  description: S1-PE03_Ethernet2
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.11/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet4
  peer: s1-pe04
  peer_interface: Ethernet2
  description: S1-PE04_Ethernet2
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.15/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

# --------------------------------- #
# TO P INTERFACES
# --------------------------------- #

- name: Ethernet5
  peer: s1-p01
  peer_interface: Ethernet5
  description: S1-P01_Ethernet5
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.0.1/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet6
  peer: s2-p02
  peer_interface: Ethernet6
  description: S2-P02_Ethernet6
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.0.8/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True