ethernet_interfaces:
- name: Ethernet1
  peer: s1-p01
  peer_interface: Ethernet4
  description: S1-P01_Ethernet4
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.12/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet2
  peer: s1-p02
  peer_interface: Ethernet4
  description: S1-P02_Ethernet4
  shutdown: false
  mtu: 1500
  type: routed
  ip_address: 10.0.1.14/31
  isis_enable: "CORE-ISIS"
  isis_network_point_to_point: True

- name: Ethernet4
  peer: s1-ce01
  shutdown: False
  channel_group:
    id: 4
    mode: "active"

vlan_interfaces:
- name: "Vlan1810"
  description: vrf-FW-HA-xco-firewall-site01
  shutdown: False
  vrf: FW-HA
  ip_address: "10.18.10.{{ device_id }}/24"
  ip_virtual_router_addresses:
    - "10.18.10.1"

port_channel_interfaces:
- name: Port-Channel4
  description: to s1-ce02 - firewall test - vrrp
  mode: "trunk"
  vlans: "1810"
  evpn_ethernet_segment:
    identifier: 0000:0000:0101:0101:0202
    mpls:
      shared_index: 100
    route_target: 01:01:01:01:02:02
    designated_forwarder_election:
      hold_time: 1
  lacp_id: 0101.0101.0202
