vlans:
  - id: 1811
    name: "S2-REMOTE-END-XCO"
    tenant: "FW-HA"

  - id: 2002
    name: "BKP-SITE02"
    tenant: "BKP"

vrfs:
  - name: FW-HA
    description: FW-HA VRF
    ip_routing: True
  - name: BKP
    description: BACKUP VRF
    ip_routing: True

ethernet_interfaces:
- name: Ethernet1
  peer: s2-pe01
  description: to s2-pe01 - CLIENT use-case - Remote end
  vlans: "1811, 2002"
  mode: "trunk"

vlan_interfaces:
- name: "Vlan1811"
  description: vrf-FW-HA-xco-firewall-site01
  shutdown: False
  vrf: FW-HA
  ip_address: "10.18.11.{{ device_id }}/24"

- name: "Vlan2002"
  description: vrf-bkp-xco-site02
  shutdown: False
  vrf: BKP
  ip_address: "10.200.2.{{ device_id }}/24"

static_routes:
- vrf: FW-HA
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.18.11.1
- vrf: BKP
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.200.2.1
- vrf: default
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.2.1