hostname: "{{ inventory_hostname }}"

management_interfaces:
  - name: Management0
    description: oob_management
    shutdown: false
    vrf: "{{ management_vrf_name }}"
    ip_address: "{{ ansible_host }}/24"
    gateway: 192.168.2.1
    type: oob

# Static routes within Management VRF
static_routes:
  - vrf: "{{ management_vrf_name }}"
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.2.1

service_routing_protocols_model: multi-agent
ip_routing: true

vrfs:
  - name: default
    ip_routing: true
  - name: "{{ management_vrf_name }}"
    ip_routing: true
