hostname: "{{ inventory_hostname }}"

static_routes:
- vrf: default
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.2.1

management_ssh:
  enable: True
  vrfs:
    - name: default
      enable: True

# dns servers.
name_servers:
  - 192.168.2.1
  - 8.8.8.8

timezone: Europe/Paris
ntp:
  local_interface:
    name: Management0
    vrf: default
  servers:
    - name: fr.pool.ntp.org
      preferred: True
      local_interface: Management0
      vrf: default
      burst: True
      iburst: True
    - name: uk.pool.ntp.org
      local_interface: Management0
      vrf: default
      burst: True
      iburst: True

# dns domain
dns_domain: atd.lab

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
# ntp_servers:
#  - 192.168.0.1

aaa_authorization:
  exec:
    default: local

service_routing_protocols_model: multi-agent
ip_routing: true

vrfs:
- name: default
  ip_routing: true


management_interfaces:
- name: Management0
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: "{{ ansible_host }}/24"
  gateway: 192.168.2.1
  type: oob

management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true

aliases: |
  alias ale show ip hardware ale routes unprogrammed
  alias ale6 show ipv6 hardware ale routes unprogrammed
  alias cc clear counters
  alias fabric show platform fap fabric rates mbps
  alias fib show ip hardware fib routes | grep bgp | wc -l
  alias fib6 show ipv6 hardware fib routes | grep bgp | wc -l
  alias l3 show platform sand l3 summary
  alias route6sum show ipv6 route summary
  alias routesum show ip route summary
  alias senz show interface counter error | nz
  alias shmc show int | awk '/^[A-Z]/ { intf = $1 } /, address is/ { print intf, $6 }'
  alias snz show interface counter | nz
  alias spd show port-channel %1 detail all
  alias sli show lacp interface Ethernet %1 detailed
  alias sqnz show interface counter queue | nz
  alias srnz show interface counter rate | nz
  alias summary show bgp summary

