vlans:

ethernet_interfaces:
  - name: Ethernet1
    description: to s1-pe01 ethernet4
    vlans: "1-4094"
    mode: "trunk"

port_channel_interfaces:

vlan_interfaces:
# - name: "Vlan1810"
#   description: vrf-FW-HA-xco-firewall-site01
#   shutdown: False
#   vrf: FW-HA
#   ip_address: "10.18.10.{{ device_id }}/24"
#   vrrp_ids:
#     - id: 10
#       priority_level: 100
#       ipv4:
#         address: 10.18.10.254
#         version: 3

# - name: "Vlan2001"
#   description: vrf-bkp-xco-site01
#   shutdown: False
#   vrf: BKP
#   ip_address: "10.200.1.{{ device_id }}/24"

static_routes:
  - vrf: "{{ management_vrf_name }}"
    destination_address_prefix: 0.0.0.0/0
    gateway: 192.168.2.1